language: go
go:
  - "1.16"

env:
  - env GO111MODULE=on

script:
  - go mod vendor
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)